tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary": "#c180ff",
              "error-dim": "#d7383b",
              "tertiary-fixed": "#53ddfc",
              "error-container": "#9f0519",
              "tertiary-container": "#53ddfc",
              "surface-container-highest": "#192540",
              "on-primary-fixed": "#000000",
              "primary-container": "#6e9fff",
              "outline": "#6d758c",
              "on-secondary-container": "#e9cdff",
              "primary-dim": "#699cff",
              "on-tertiary": "#005464",
              "on-tertiary-fixed": "#003640",
              "surface-container-high": "#141f38",
              "inverse-surface": "#faf8ff",
              "tertiary-dim": "#40ceed",
              "on-error-container": "#ffa8a3",
              "surface-bright": "#1f2b49",
              "secondary-fixed-dim": "#dbb4ff",
              "on-background": "#dee5ff",
              "on-primary-container": "#002150",
              "on-primary-fixed-variant": "#002a62",
              "tertiary": "#8ce7ff",
              "inverse-on-surface": "#4d556b",
              "primary-fixed-dim": "#5391ff",
              "surface-container": "#0f1930",
              "outline-variant": "#40485d",
              "secondary-fixed": "#e5c6ff",
              "primary": "#85adff",
              "primary-fixed": "#6e9fff",
              "surface-dim": "#060e20",
              "on-primary": "#002c66",
              "on-secondary-fixed": "#4f0089",
              "on-error": "#490006",
              "on-tertiary-container": "#004b58",
              "inverse-primary": "#005bc4",
              "surface-container-lowest": "#000000",
              "surface-variant": "#192540",
              "tertiary-fixed-dim": "#40ceed",
              "surface": "#060e20",
              "secondary-container": "#6f00be",
              "secondary-dim": "#9c48ea",
              "on-secondary-fixed-variant": "#7511c3",
              "on-surface": "#dee5ff",
              "on-secondary": "#33005b",
              "surface-tint": "#85adff",
              "surface-container-low": "#091328",
              "on-tertiary-fixed-variant": "#005564",
              "on-surface-variant": "#a3aac4",
              "background": "#060e20",
              "error": "#ff716c"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
      }
    },
  },
}
